    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.EventChat;
import Controller.PublicEnvent;
import ModelClient.Model_Recive_Message;
import ModelClient.Model_Send_Message;
import ModelClient.Model_User_Account;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author FPTSHOP
 */
public class Chat extends javax.swing.JPanel {

    /**
     * Creates new form Home_Left
     */
    private Chat_Title chatTitle ;
    private Chat_Body chatBody  ;
    private Chat_Bottom chatBottom ;
    public Chat() {
        initComponents();
        init();
    }
    private void init() {
        setLayout(new MigLayout("fillx", "0[fill]0", "0[]0[100%, fill]0[shrink 0]0"));
        chatTitle = new Chat_Title();
        chatBody = new Chat_Body();
        chatBottom = new Chat_Bottom();
        PublicEnvent.getInstance().addEventChat(new EventChat() {
            @Override
            public void sendMessage(Model_Send_Message data) {
                chatBody.addImtemRight(data);
            }

            @Override
            public void receviedMessage(Model_Recive_Message data) {
                if (chatTitle.getUser().getEmail().equals(data.getFromEmail())) {
                    SoundEffect.MessageReceive.play();
                    chatBody.addImtemLeft(data);
                }
            }
        });
        add(chatTitle, "wrap");
        add(chatBody, "wrap");
        add(chatBottom, "h ::50%");
    }
     public void setUser (Model_User_Account user) {
        chatTitle.setUserName(user);
        chatBottom.setUser(user);
        chatBody.clearChat();
    }
     public void updateUser (Model_User_Account user) {
         chatTitle.updateUser(user) ;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 833, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
