/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.PublicEnvent;
import ModelClient.Model_File_Sender;
import ModelClient.Model_Receive_Image;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.SwingUtilities;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author FPTSHOP
 */
public class Chat_Image extends javax.swing.JLayeredPane {

    private String src;
    private ImageIcon image;

    public ImageIcon getImage() {
        return image;
    }
    
    /**
     * Creates new form Chat_Image
     */
    public Chat_Image(boolean right) {
        initComponents();
        setLayout(new MigLayout("", "0[" + (right ? "right" : "left") + "]0", "3[]3"));
    }
//    thêm hình ảnh vào một giao diện người dùng 

    public void addImage(Model_File_Sender fileSender) { // nhận một hoặc nhiều đối số kiểu Icon , cho phép truyền vào một mảng biến động các đối số kiểu icon 
            image = new ImageIcon(fileSender.getFile().getAbsolutePath()) ;
            src = fileSender.getFile().getAbsolutePath() ;
            Image_Item pic = new Image_Item() ;
            pic.setPreferredSize(getAutoSize(image, 200, 200));
            pic.setImage(image ,fileSender);
            addEvent(pic, image);
            add(pic, "wrap");

    }
        public void addImage(Model_Receive_Image dataImage) { // nhận một hoặc nhiều đối số kiểu Icon , cho phép truyền vào một mảng biến động các đối số kiểu icon 
            Image_Item pic = new Image_Item();
            pic.setPreferredSize(new Dimension(dataImage.getWidth() , dataImage.getHeight()));
            pic.setImage(dataImage);
            addEvent(pic, getImage());
            add(pic, "wrap");

    }
//    xử lý sự kiện khi nhấp chuột trái vào hình ảnh 
    private void addEvent(Component com, Icon image) {
        com.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        com.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (SwingUtilities.isLeftMouseButton(e)) {
                    PublicEnvent.getInstance().getEventImageView().viewImage(image);
                }
            }

        });
    }
// tính toán kích thước thích hợp cho một hình ảnh để hiển thị trong thành phần chứa nhưng vẫn giữ nguyên tỉ lệ khung hình 
    private Dimension getAutoSize(Icon image, int w, int h) {
 //        check xem thử w , h của hình ảnh có lớn hơn hình ảnh thực tế hay không
        if (w > image.getIconWidth()) {
            w = image.getIconWidth();
        }
        if (h > image.getIconHeight()) {
            h = image.getIconHeight();
        }
        int iw = image.getIconWidth();
        int ih = image.getIconHeight();
        double xScale = (double) w / iw;
        double yScale = (double) h / ih;
        double scale = Math.min(xScale, yScale);
        int width = (int) (scale * iw);
        int height = (int) (scale * ih);
        return new Dimension(width, height);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
